Pkcs11 sessions fix master
hyperledger/fabric pull request #1047
Opened 2020-04-09 18:52 UTC by mrshah-at-ibm

Signed-off-by: Mihir Shah <mrshah@us.ibm.com>

#### Type of change

- Bug fix

#### Description

Making the same change from https://github.com/hyperledger/fabric/pull/1022 into master

As described in [JIRA FAB-17722](https://jira.hyperledger.org/browse/FAB-17722):
Currently the pkcs11 code in fabric's bccsp module is set to have a session cache and reuse sessions if available in cache. If a session goes bad (due to connection issues with HSM), the session is not evicted from cache and will be reused. If all sessions go bad, the client will never be able to recover and keep using bad sessions.

#### Additional details

This code change:
- Moves creation of a new session to a new function `CreateSession`
- Validates the existing session by calling `GetSessionInfo`
- If found invalid, creates a new session and expects the old one to be garbage collected.
- The current test in pkcs11_test.go `TestPKCS11GetSession`, will test the new function as well. Let me know if I should add additional test to test `CreateSession` function.

#### Related issues

https://github.com/hyperledger/fabric/pull/1022
https://jira.hyperledger.org/browse/FAB-17722

2020-04-09 19:59 UTC, sykesm commented
LGTM; please squash your commits. Thanks.

2020-04-10 12:56 UTC, mastersingh24 commented on bccsp/pkcs11/pkcs11.go
> +			session = createSession(csp.ctx, csp.slot, csp.pin)
w/o doing some major surgery, this looks ok to me.  the pool should eventually end up with valid sessions.
probably would be good if we could actually recreate the entire ctx, but that's a redesign.

2020-04-10 13:17 UTC, sykesm requested changes
Still LGTM; just marking this to prevent merging before the commits are squashed. Thanks!

2020-04-13 13:09 UTC, mrshah-at-ibm commented
> Still LGTM; just marking this to prevent merging before the commits are squashed. Thanks!

Squashed. Thank you!

2020-04-13 13:50 UTC, sykesm approved these changes

2020-04-13 14:36 UTC, merged

2020-05-13 18:48 UTC, btl5037 commented
@Mergifyio backport release-2.0

2020-05-13 18:48 UTC, btl5037 commented
@Mergifyio backport release-2.1