rm DB interface from privacyenabledstate pkg
hyperledger/fabric pull request #1242
Opened 2020-05-12 15:57 UTC by cendhu

#### Type of change

- Improvement (improvement to code)

#### Description

As part of [FAB-10794](https://jira.hyperledger.org/browse/FAB-10794), we would be making changes to `LoadCommittedVersions()`. Before doing that, we remove `DB` interface from the `privacyenabledstate` pkg (which includes LoadCommittedVersions() API) as it has a single implementation only. Only when we need to have multiple implementations, we need an interface. Otherwise, it just adds unnecessary difficulties during code navigation and casting such as `db.(*privacyenabledstate.CommonStorageDB)` in the test.

As we remove `DB` interface, the filename `db.go` does not make sense. Hence, we rename it to `types.go` as it holds all private data related types. Further, `db_test.go` contains tests that
should be in `common_storage_db_test.go`. Hence, we also move those test to the correct location and rename `db_test.go` to `types_test.go`.

#### Additional details

Two commits have been pushed to ease the review process. 

#### Related issues

[FAB-17880](https://jira.hyperledger.org/browse/FAB-17880)

2020-05-12 18:05 UTC, manish-sethi requested changes
Discussed offline with @cendhu for some further changes - so, holding this for now.

2020-05-14 02:44 UTC, manish-sethi approved these changes
Just some nit comments on a couple variable names. But would not like to hold this PR for that.

2020-05-14 02:44 UTC, manish-sethi commented on core/ledger/kvledger/kv_ledger_provider.go
> +	db, err := p.dbProvider.GetDBHandle(ledgerID)
In the lines of above comment, `statedb` may be a better choice, if not `vDB`. Plain `db` looses the context.

2020-05-14 02:44 UTC, manish-sethi commented on core/ledger/kvledger/kv_ledger_provider.go
> +	dbProvider           *privacyenabledstate.DBProvider
Given that we have more than one stores, I feel that the earlier name `vdbProvider` was clearer. If you want to change, then `statedbProvider` may be a better choice in order to retain the context.

2020-05-14 02:44 UTC, merged

2020-05-14 16:31 UTC, cendhu commented
Thanks, @manish-sethi I agree with the suggested changes and have created https://jira.hyperledger.org/browse/FAB-17896 to address the review comments.