Fixed write_first_app.rst typo
hyperledger/fabric pull request #1329
Opened 2020-05-25 16:43 UTC by pratikpatil024

#### Type of change

- Documentation update

#### Description

I was going through the documentation and found a typo in the "Writing Your First Application" tutorial (write_first_app.rst file).
I hope it will help fellow learners.

2020-05-25 16:57 UTC, ale-linux requested changes
Thanks for your contribution! Please add your DCO, see here
https://github.com/hyperledger/fabric/pull/1329/checks?check_run_id=706881720

2020-05-25 17:14 UTC, pratikpatil024 commented
Thanks you @ale-linux , I did the needful changes

2020-05-25 17:17 UTC, ale-linux approved these changes

2020-05-25 17:18 UTC, merged

2020-05-26 15:42 UTC, nikhil550 commented
@Mergifyio backport release-2.1