fix infinite loop during open-ended range query -- CouchDB
hyperledger/fabric pull request #1347
Opened 2020-05-28 15:25 UTC by cendhu

#### Type of change

- Bug fix

#### Description

We use a single scanner for achieving both paginated and non-paginated range query.

We have `internalQueryLimit` and `pageSize`. The internalQueryLimit controls the number of records fetched per REST API call. The pageSize controls the total number of records needed by the caller. 

A range query is done by performing `_all_docs?startKey="XXX"&endKey="YYY"` REST API call to CouchDB. The iterator fetches almost `internalQueryLimit` number of records by appending `limit=internalQueryLimit` to the REST API.

In the following two cases, iterator would perform REST API call multiple times.

1. When the requested pageSize is higher than the internalQueryLimit 
2. When the total number of records present in the given range is higher than the internalQueryLimit

 The iterator would execute the query again once the records fetched in the first cycle are consumed and so on. In order to do that, after the execution of the REST API in each cycle, the iterator updates the initially passed `startKey` to the nextStartKey. If there is no nextStartKey, it is set to the `endKey`. Currently, when the nextStartKey and `endKey` are the same, we still run one REST API call which is actually not needed as we always set inclusive_end=false. However, this causes an infinite loop in the following case. 

When we want to retrieve all the records, the user would submit an open-ended query by passing an empty string as the `startKey` and the `endKey`. When the `startKey` is an empty string, the REST API call would become `_all_docs?endKey="YYY"`. When both are empty, it would become `_all_docs`. Given that we set the `startKey` to the `endKey` when there is no nextStartKey and still execute one REST API call after that, it gets into an infinite loop by fetching all records again and again.

In this PR, we avoid this infinite loop by setting `scanner.exhausted = true` when the `startKey` and `endKey` become the same when there is no `nextStartKey`.

#### Additional details

- We would use an open-ended range query while exporting data out of CouchDB for snapshotting.
- If desired, in a separate PR, the integration test would be added. 

#### Related issues

[FAB-17939](https://jira.hyperledger.org/browse/FAB-17939)

2020-05-28 23:21 UTC, manish-sethi requested changes

2020-05-29 02:22 UTC, cendhu commented on core/ledger/kvledger/txmgmt/statedb/statecouchdb/statecouchdb.go
> +	if scanner.queryDefinition.endKey == nextStartKey {
The `nextStartKey` would never be greater than the `endKey`. The current condition is very generic. When the scanner is exhausted, `nextStartKey == endKey` would always become true and any condition that we have after this condition would become a deadcode.

2020-05-29 02:26 UTC, cendhu commented on core/ledger/kvledger/txmgmt/statedb/statecouchdb/statecouchdb.go
> +	if scanner.queryDefinition.endKey == nextStartKey {
As mentioned in the PR description, the current condition check avoids an additional REST API call once the scanner is exhaused. Let's assume `startKey = "marble1" `and `endKey = "marble5"`. It is possible that the `startKey` and `endKey` would become the same, i.e., marble5. Once it has become the same, there is no need to run an additional REST API call.  The current condition takes care of all scenarios.

2020-05-29 03:42 UTC, manish-sethi commented on core/ledger/kvledger/txmgmt/statedb/statecouchdb/statecouchdb.go
> +	if scanner.queryDefinition.endKey == nextStartKey {
Ah, yes. just looked at the code and found this logic of explicitly returning the end key as next start, deep buried :-) Thanks for the explanation. I feel the logic of limits and pagination is much spread across functions and needs a refactoring.

2020-05-29 03:43 UTC, manish-sethi approved these changes

2020-05-29 03:43 UTC, merged

2020-05-29 03:53 UTC, cendhu commented on core/ledger/kvledger/txmgmt/statedb/statecouchdb/statecouchdb.go
> +	if scanner.queryDefinition.endKey == nextStartKey {
Thanks, Manish, for merging this. I agree. It is much spread and complex to read.