Removing viper lib from viperutil/config_util.go
hyperledger/fabric pull request #1392
Opened 2020-06-11 16:14 UTC by nbasker

#### Type of change

- Improvement (improvement to code and performance by avoiding viper library)

#### Description

There is overlap between in the implementation of
`getKeysRecursively` and the viper.Get() implementation.
The viper does yaml.Unmarshal and stores in viper.config,
which is provided to getKeysRecursively and further sub-keys
are available readily and there is no need to fetch
through viper.Get(). Towards the overall objective of
moving away from viper, its usage here can be removed.

There is further cleanup required to remove viper, but this is a draft PR for review and get alignment on the changes. The code flow in corresponding to
execmode := os.Getenv("SKIP_VIPER") being set has the VIPER removed.

#### Additional details

After the change executed unit tests for internal/configtxgen/genesisconfig, orderer/common/localconfig and common/viperutil which use the functions EnhancedExactUnmarshal()/getKeysRecursively()

go test -race -count 1 -v -run Test github.com/hyperledger/fabric/internal/configtxgen/genesisconfig | tail -2
PASS
ok      github.com/hyperledger/fabric/internal/configtxgen/genesisconfig        10.481s
SKIP_VIPER=yes go test -race -count 1 -v -run Test github.com/hyperledger/fabric/internal/configtxgen/genesisconfig | tail -2
PASS
ok      github.com/hyperledger/fabric/internal/configtxgen/genesisconfig        5.922s

go test -race -count 1 -v -run Test github.com/hyperledger/fabric/orderer/common/localconfig | tail -2
PASS
ok      github.com/hyperledger/fabric/orderer/common/localconfig        5.639s
SKIP_VIPER=orderer go test -race -count 1 -v -run Test github.com/hyperledger/fabric/orderer/common/localconfig | tail -2
PASS
ok      github.com/hyperledger/fabric/orderer/common/localconfig        5.418s

go test -race -count 1 -v -run Test github.com/hyperledger/fabric/common/viperutil | tail -2
PASS
ok      github.com/hyperledger/fabric/common/viperutil  5.544s
SKIP_VIPER=viperutil go test -race -count 1 -v -run Test github.com/hyperledger/fabric/common/viperutil | tail -2
PASS
ok      github.com/hyperledger/fabric/common/viperutil  5.558s

#### Related issues

https://jira.hyperledger.org/browse/FAB-17508

2020-06-12 04:37 UTC, nbasker commented
Manually ran the same test case a few times and it passed. Shall resubmit with further cleanup after getting review feedback.

go test -race -count 1 -v -run Test github.com/hyperledger/fabric/orderer/consensus/etcdraft 
<--snip-->                                                                                                                                                      
••2020-06-12 09:10:02.116 IST [test] HandleChain -> INFO 02b EvictionSuspicion not set, defaulting to 10m0s
•                                                                                
Ran 105 of 105 Specs in 44.319 seconds                                           
SUCCESS! -- 105 Passed | 0 Failed | 0 Pending | 0 Skipped                
--- PASS: TestEtcdraft (44.32s)

2020-06-16 23:21 UTC, denyeart commented
Tagging @sykesm for review since the PR is related to a Jira he opened.

2020-06-23 22:10 UTC, sykesm reviewed
Thanks for the PR. Sorry for the delay in reviewing. I've been focusing on other things.

Looks like the approach you've taken is to extract a bunch of code from viper and inlined it into the `viperutil` package. While normally I'd push back on that because we wouldn't benefit from the enhancements and fixes from that community, but, given we're stuck on an ancient version, it's probably good enough.

My goal is to do a detailed review over the next day or two. Based on my quick glance, I think there are a few things that were pulled over that we simply don't need and that should be removed (e.g. `SetConfigType`, `AutomaticEnv`), there are some idiomatic Go changes that I'd like to see, and there are tests that need to be backfilled.

2020-06-24 17:13 UTC, sykesm requested changes
Given the approach is to stop using viper, we don't need to maintain the generalizations implied by viper.  That means a number of methods can be removed and/or unexported.

Also, since this is not tied to viper, the package should be renamed to something other than `viperutil`.  I'm not sure what the best name so it's probably best to address the other comments first.

Thanks.

2020-06-24 17:13 UTC, sykesm commented on common/viperutil/config_util.go
> +}
This function is only used by `EnhancedExactUnmarshal` and can probably be unexported.

2020-06-24 17:13 UTC, sykesm commented on common/viperutil/config_util.go
> +func EnhancedExactUnmarshal(c *ConfigParser, output interface{}) error {
This is no longer a function around viper so it should be converted into a method on `ConfigParser`.

2020-06-24 17:13 UTC, sykesm commented on orderer/common/localconfig/config.go
> +	//"github.com/spf13/viper"
please remove commented out code

2020-06-25 03:50 UTC, nbasker commented
> Thanks for the PR. Sorry for the delay in reviewing. I've been focusing on other things.
> 
> Looks like the approach you've taken is to extract a bunch of code from viper and inlined it into the `viperutil` package. While normally I'd push back on that because we wouldn't benefit from the enhancements and fixes from that community, but, given we're stuck on an ancient version, it's probably good enough.
> 
> My goal is to do a detailed review over the next day or two. Based on my quick glance, I think there are a few things that were pulled over that we simply don't need and that should be removed (e.g. `SetConfigType`, `AutomaticEnv`), there are some idiomatic Go changes that I'd like to see, and there are tests that need to be backfilled.

Shall be addressing the review comments and raising a PR in the next few days.

2020-06-27 02:58 UTC, nbasker commented
I still need to take care of a few more changes given, shall post once all the changes are taken care.

2020-06-27 13:38 UTC, nbasker commented
Addressed all the code review comments and updated the PR.
Regarding the tests that need to be backfilled, should it be around the ConfigParse methods.
Further, instead of viperutil, this can be moved into common/configparse/configparse.go and configparse_test.go to reflect that it is not viperutil anymore (or any other better name).
Since the dependency between viperutil.EnhancedExactUnmarshal() and viper is removed, updating the viper to latest can also be considered.

2020-06-29 18:23 UTC, sykesm reviewed
It's looking a lot better. Let's get these comments taken care of and we can discuss other changes as follow-on PRs.

2020-06-29 18:23 UTC, sykesm commented on common/viperutil/config_util.go
> +		logger.Debugf("Checking for ", fullPath)
Same here. I don't see the need but, if we have it, it should be the correct variant.

2020-06-29 18:23 UTC, sykesm commented on common/viperutil/config_util.go
> +			logger.Debugf("Found: ", fullPath)
Same here. I don't see the need but, if we have it, it should be the correct variant.

2020-06-29 18:23 UTC, sykesm commented on common/viperutil/config_util.go
> +	logger.Debugf("Searching for config in ", in)
I don't believe we need the debug information but, if it's here, it should be the correct variant. Debugf uses a Printf style format string and value and that's not what's here.

Looks like I need to update the linter.

2020-06-29 18:23 UTC, sykesm commented on common/viperutil/config_util.go
> +	logger.Debugf("Searching for config in ", c.configPaths)
I don't believe this debug is needed.

2020-06-29 19:38 UTC, sykesm commented
Looks like I forgot to request that you squash your commits. This change should be contained in a single commit. Thanks.

2020-06-30 11:18 UTC, nbasker commented
> It's looking a lot better. Let's get these comments taken care of and we can discuss other changes as follow-on PRs.

2020-06-30 11:18 UTC, closed without merging

2020-06-30 11:22 UTC, nbasker commented
> Looks like I forgot to request that you squash your commits. This change should be contained in a single commit. Thanks.

Tried squashing my commits, but in between had done a merge from master to sync the bugfix branch, in the process messed up the squash. I am going to drop this PR and the branch and raise a fresh one. Shall include all the latest review comments including "file as the reader to ReadConfig" which got missed earlier.