[FAB-17374] Integration test for Chaincode as an External Service
hyperledger/fabric pull request #1510
Opened 2020-07-01 03:37 UTC by psingh-io

**Type of change**
Test update

**Details**
Fixes the issues reported in PR for Chaincode as External Service. The original PR with comments is here:
https://github.com/hyperledger/fabric/pull/552

The test is in integration/e2e/chaincode_service_test.go file

2020-07-01 14:32 UTC, sykesm requested changes
Thank you for reviving this.

There's still a lot of extra boilerplate and customization that should not be necessary. I'm also very keen on isolating the changes to the `nwo` package to what is necessary and reusable. In particular, the addition of `DeployWithoutInitialization` isn't necessary because we can simply pass the chaincode struct to `DeployChaincode` after disabling `InitRequired`.

When it comes to error checking within tests, we do want assertions on errors to make sure things go as expected. There are a lot of places where that checking is missing. These need to be addressed.

Before merging this, we should also get the duration marshaling bug fixed.

I'll be on the lookout for changes.

2020-07-01 14:32 UTC, sykesm commented on integration/e2e/chaincode_service_test.go
> +	clientCAFile := filepath.Join(certsDir, "clientCA.pem")
error checks?

2020-07-01 14:32 UTC, sykesm commented on integration/nwo/deploy.go
> +// where package code is required for stating the external chaincode service.
This condition is for exactly one scenario. It doesn't warrant duplicating `DeployChaincode` in the same package that hods it.

2020-07-01 14:32 UTC, sykesm commented on integration/e2e/chaincode_service_test.go
> +}
Why functions for these instead of vars in the test setup?  They should be calculated once.

2020-07-01 14:32 UTC, sykesm commented on integration/e2e/chaincode_service_test.go
> +			})
I don't understand why we need to augment the network before generating the config. I don't see anything in here referring to `baseprofilechannel`. Can you please elaborate on why this is needed or modify the test to use the out of the box `BasicSolo` config?

2020-07-01 14:32 UTC, sykesm commented on integration/e2e/chaincode_service_test.go
> +			}
Why  do we need to do this? We already have other tests that assert we can operate a peer without a docker configuration.

2020-07-01 21:48 UTC, psingh-io commented
> Thank you for reviving this.
> 
> There's still a lot of extra boilerplate and customization that should not be necessary. I'm also very keen on isolating the changes to the `nwo` package to what is necessary and reusable. In particular, the addition of `DeployWithoutInitialization` isn't necessary because we can simply pass the chaincode struct to `DeployChaincode` after disabling `InitRequired`.
> 
> When it comes to error checking within tests, we do want assertions on errors to make sure things go as expected. There are a lot of places where that checking is missing. These need to be addressed.
> 
> Before merging this, we should also get the duration marshaling bug fixed.
> 
> I'll be on the lookout for changes.

@sykesm Thanks for reviewing and your feedback. I will update the with required changes in a day or two.

2020-07-06 18:57 UTC, sykesm commented
@psingh-io Two small things.

1. Looks like there's a problem highlighted by the linter.
2. We'd prefer to see pull requests without merge commits.

Can you please address the problem and rebase on top of master instead of merging master?

2020-07-07 14:18 UTC, psingh-io commented
Thanks for reviewing. I will make these updates today.

Pancham

On Mon, Jul 6, 2020 at 1:57 PM Matthew Sykes <notifications@github.com>
wrote:

> @psingh-io <https://github.com/psingh-io> Two small things.
>
>    1. Looks like there's a problem highlighted by the linter.
>    2. We'd prefer to see pull requests without merge commits.
>
> Can you please address the problem and rebase on top of master instead of
> merging master?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/hyperledger/fabric/pull/1510#issuecomment-654409782>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQB2SF6MBERU64ZZRUGHN5DR2INCRANCNFSM4OM7UDDQ>
> .
>

2020-07-08 14:54 UTC, sykesm commented
@psingh-io May I fixup your commits and push so I can merge this in sort order?

2020-07-08 16:13 UTC, psingh-io commented
Yes, please.

I did rebase and cleaned up commit history by squashing in one. But, there
were 2 commits still showing. When I tried to squash the last two, I was
getting merges in commit history and hence had reverted.

Thanks for your help.
Pancham

On Wed, Jul 8, 2020, 9:54 AM Matthew Sykes <notifications@github.com> wrote:

> @psingh-io <https://github.com/psingh-io> May I fixup your commits and
> push so I can merge this in sort order?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/hyperledger/fabric/pull/1510#issuecomment-655570360>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQB2SFYMJ7VQF3UYGVWIX3TR2SCDPANCNFSM4OM7UDDQ>
> .
>

2020-07-09 03:19 UTC, sykesm approved these changes

2020-07-09 03:19 UTC, merged