Update docs to replace fabcar references with basic asset transfer
hyperledger/fabric pull request #1763
Opened 2020-08-18 20:37 UTC by stephyee

#### Type of change

- Documentation update

#### Description

Replace any fabcar references with basic asset transfer samples.

2020-08-18 21:51 UTC, denali49 requested changes
Please be advised that this work has already been completed, merged into master, and is in the process of being backported to 2.x branches.  Might be best to delete this PR and wait to see if we missed anything after backporting is completed.  Thanks for working this though.

2020-08-19 11:28 UTC, denali49 approved these changes
I reviewed after backporting my PR to the 2.2 branch.  You are correct with the changes recommended with this PR.  Thanks for doing this and apologies for the confusion.

2020-08-19 12:50 UTC, ale-linux approved these changes

2020-08-19 12:52 UTC, ale-linux approved these changes

2020-08-19 12:52 UTC, merged

2020-08-20 14:04 UTC, denyeart commented
@mergifyio backport release-2.2