[FAB-18188] Log orderer and peer cert expiration date upon startup
hyperledger/fabric pull request #1804
Opened 2020-08-25 22:24 UTC by denyeart

#### Type of change

- Improvement (improvement to logging)

#### Description

FAB-17000 added a warning if expiration is within a week.

This change additionally info logs the future enrollment, tls server, and tls client
cert expiration dates upon startup, regardless of whether they will expire within a week or not.

Signed-off-by: David Enyeart <enyeart@us.ibm.com>

2020-08-25 22:37 UTC, yacovm requested changes
I don't understand why modify the current code and make it even more complex.

Why not just export [certExpirationTime](https://github.com/hyperledger/fabric/blob/f54d3cda30c731b55981d7029b819e22fce4bf06/common/crypto/expiration.go#L31) and log it [outside](https://github.com/hyperledger/fabric/blob/01d28e583c2588dac1961d38750a4ec491725e6a/orderer/common/server/main.go#L199)?

2020-08-26 00:06 UTC, denyeart commented
@yacovm Because each of the three certs have checks against them in TrackExpiration, as does certExpirationTime(). Why duplicate all those checks and add complexity to the peer and orderer mains, when it can be done together with the existing logging in the dedicated expiration tracking function where people would expect it. At the end of the day, I don't think it matters much either way, but mostly I'd prefer to keep the mains nice and clean.

2020-08-26 09:12 UTC, yacovm commented
> @yacovm Because each of the three certs have checks against them in TrackExpiration, as does certExpirationTime(). Why duplicate all those checks and add complexity to the peer and orderer mains, when it can be done together with the existing logging in the dedicated expiration tracking function where people would expect it. At the end of the day, I don't think it matters much either way, but mostly I'd prefer to keep the mains nice and clean.

I think that if you make a single function that accepts all 3 as inputs (similar to track expiration) then it won't pollute the main, and will be much easier to understand the code.

2020-08-26 11:51 UTC, denyeart commented
> > @yacovm Because each of the three certs have checks against them in TrackExpiration, as does certExpirationTime(). Why duplicate all those checks and add complexity to the peer and orderer mains, when it can be done together with the existing logging in the dedicated expiration tracking function where people would expect it. At the end of the day, I don't think it matters much either way, but mostly I'd prefer to keep the mains nice and clean.
> 
> I think that if you make a single function that accepts all 3 as inputs (similar to track expiration) then it won't pollute the main, and will be much easier to understand the code.

@yacovm  But all three cert expiration dates are not available for logging, it depends on which are configured on the node. By the time we duplicate that logic, might as well just log it alongside the expiration Warning where I have it. I'm not seeing the complexity of keeping the expiration warning and expiration logging co-located in trackCertExpiration(), on the contrary it seems that a trackCertExpiration() function is the most straightforward place to both log the date and provide a warning if the date is coming soon.

2020-08-26 13:32 UTC, yacovm approved these changes

2020-08-26 13:32 UTC, merged

2020-08-26 13:41 UTC, denyeart commented
@Mergifyio backport release-2.2

2020-08-26 13:41 UTC, denyeart commented
@Mergifyio backport release-2.1

2020-08-26 13:41 UTC, denyeart commented
@Mergifyio backport release-2.0