Pass unreconciled missing data info to ledger
hyperledger/fabric pull request #1858
Opened 2020-09-08 03:47 UTC by cendhu

#### Type of change

- New feature

#### Description

Reconciler needs to pass the unreconciled missing data info to the ledger so that the ledger can deprioritize these unreconcilable data.

2020-09-11 01:15 UTC, denyeart requested changes, later dismissed
This PR is not working since the unreconciled data isn't passed down to pvtdataStore.CommitPvtDataOfOldBlocks().
Once I added that in my local copy, it works as intended.

Not sure how I missed this in the master PR, since I thought I ran the same test, but it looks like the same fix is needed in master.

2020-09-11 01:15 UTC, denyeart commented on core/ledger/kvledger/kv_ledger.go
> +	err = l.pvtdataStore.CommitPvtDataOfOldBlocks(hashVerifiedPvtData, nil)
```suggestion
	err = l.pvtdataStore.CommitPvtDataOfOldBlocks(hashVerifiedPvtData, unreconciled)
```

2020-09-11 02:10 UTC, cendhu commented
> This PR is not working since the unreconciled data isn't passed down to pvtdataStore.CommitPvtDataOfOldBlocks().
> Once I added that in my local copy, it works as intended.
> 
> Not sure how I missed this in the master PR, since I thought I ran the same test, but it looks like the same fix is needed in master.

Yes. Thanks for finding this. I will push a PR to fix this and a ledger level test in `kvledger/tests`. In a separate PR, i will push an integration test.

2020-09-11 03:06 UTC, cendhu commented
> Not sure how I missed this in the master PR, since I thought I ran the same test, but it looks like the same fix is needed in master.

I think, you didn't miss it in the master. When you tried this out, the code was correct (https://github.com/hyperledger/fabric/commit/b5cd5800b4d11b373aa07af9a2b105a2470d2653#diff-cd46fbfd3be8cfa8c0cc9829455cf9fbR757) and hence, it worked for you. Sometime during the rebasing, it got changed in the master.

2020-09-16 20:27 UTC, denyeart approved these changes
With the final fix coming in a follow-on PR, I'll go ahead merge this one into release-2.2.

2020-09-16 20:27 UTC, merged