Add release notes for v1.4.9
hyperledger/fabric pull request #1902
Opened 2020-09-18 17:21 UTC by denyeart

Add release notes for v1.4.9

Signed-off-by: David Enyeart <enyeart@us.ibm.com>

2020-09-23 10:20 UTC, mastersingh24 requested changes

2020-09-23 10:20 UTC, mastersingh24 commented on release_notes/v1.4.9.md
> +The enrollment, tls server, and tls client certificate expiration dates are now logged upon peer and orderer startup.
```suggestion
The enrollment, TLS server, and TLS client certificate expiration dates are now logged upon peer and orderer startup.
```

2020-09-23 10:20 UTC, mastersingh24 commented on release_notes/v1.4.9.md
> +**peer and orderer HSM - Drain session pool before creating new sessions**
```suggestion
**peer and orderer PKCS#11 - Drain session pool before creating new sessions**
```

2020-09-23 10:20 UTC, mastersingh24 commented on release_notes/v1.4.9.md
> +If a bad hardware security module (HSM) session was retrieved from the session pool,
```suggestion
If an invalid PKCS#11  session was acquired from the session pool,
```

2020-09-23 10:20 UTC, mastersingh24 commented on release_notes/v1.4.9.md
> +a new session would be immediately created instead of attempting to retrieve another
```suggestion
a new session would be immediately created instead of attempting to acquire another
```

2020-09-23 10:20 UTC, mastersingh24 commented on release_notes/v1.4.9.md
> +**peer and orderer HSM - Add object handle cache to PKCS#11 provider**
```suggestion
**peer and orderer PKCS#11 - Add object handle cache**
```

2020-09-23 16:33 UTC, denyeart commented
All comments addressed!

2020-09-23 21:27 UTC, mastersingh24 approved these changes

2020-09-24 13:50 UTC, denyeart commented
Ok, I'll go ahead and merge... any final fixes can be added in subsequent PR.

2020-09-24 13:51 UTC, merged