[FAB-18235] Use NextCommit for deliver event in CLI cmd and handle Ne…
hyperledger/fabric pull request #1936
Opened 2020-09-28 13:34 UTC by wenjianqiao

Signed-off-by: Wenjian Qiao <wenjianq@gmail.com>

#### Type of change
- New feature

#### Description
- Use NextCommit instead of Newest when listening to deliver events in CLI cmds
- Update block iterator generation code to properly handle Newest for snapshot

#### Related issues
https://jira.hyperledger.org/browse/FAB-18235

2020-09-30 16:15 UTC, manish-sethi requested changes
LGTM, just one minor suggestion about package name

2020-09-30 16:15 UTC, manish-sethi commented on common/ledger/blockledger/fileledger/impl_test.go
> +// TODO
leftover

2020-10-01 02:03 UTC, wenjianqiao commented on common/ledger/blkstorage/test_exports.go
> +
Done

2020-10-01 13:29 UTC, wenjianqiao commented
/ci-run

2020-10-01 19:19 UTC, wenjianqiao commented
/ci-run

2020-10-01 20:42 UTC, wenjianqiao commented
/ci-run

2020-10-02 02:41 UTC, manish-sethi approved these changes, later dismissed

2020-10-02 02:45 UTC, manish-sethi commented
@wenjianqiao - I guess that this PR can be merged as is if you want. Just update the commit message to reflect the change.

2020-10-02 12:45 UTC, wenjianqiao commented
> @wenjianqiao - I guess that this PR can be merged as is if you want. Just update the commit message to reflect the change.

@manish-sethi Yes, it is safe to merge the PR as is. Meanwhile, I had to undo the change in internal/peer/chaincode/common.go (i.e., didn't change from Newest to NextCommit for chaincode invocation), because the change caused test flake. Still investigating why.

2020-10-02 21:46 UTC, wenjianqiao commented
@manish-sethi Found why IT tests failed with NextCommit option. In a distributed env, some peers may get block height after the next new block is committed. In this case, using NextCommit option will never get the block it expects. Therefore, we should keep using Newest option when waiting for next committed block. The PR is done and can be merged.

2020-10-02 22:15 UTC, manish-sethi commented
> @manish-sethi Found why IT tests failed with NextCommit option. In a distributed env, some peers may get block height after the next new block is committed. In this case, using NextCommit option will never get the block it expects. Therefore, we should keep using Newest option when waiting for next committed block. The PR is done and can be merged.

Thanks @wenjianqiao for investigating it. As this could in general be a problem with `Newest` option as well. Can you open a Jira for this. As far as the scope of this PR is concerned, we are good with the changes.

2020-10-02 22:15 UTC, manish-sethi approved these changes

2020-10-02 22:16 UTC, merged