Clarify Verify behaviour in PKCS11 Impl
hyperledger/fabric pull request #2633
Opened 2021-06-02 09:38 UTC by davidkel

Signed-off-by: D <d_kelsey@uk.ibm.com>

#### Type of change

- Improvement (improvement to code, performance, etc)
- Test update

#### Description

the pkcs11 verify implementation will never receive a pkcs11 key to be used to verify a signature, this change clarifies that in the code and adds tests for the verify implementation

2021-06-03 14:11 UTC, mastersingh24 requested changes
Hmm ... not looking for changes, but I'm not sure this assertion is true.  There is supposed to be a switch for SW verify versus verifying signatures via the PKCS11 provider.

2021-06-04 08:59 UTC, mastersingh24 commented
@davidkel  What's the genesis of this change?  We are supposed to be able to verify via the PKCS11 provider not always in SW.

2021-06-04 12:35 UTC, sykesm commented
> @davidkel What's the genesis of this change? We are supposed to be able to verify via the PKCS11 provider not always in SW.

So, in Fabric, we never get a pkcs11 key because of the MSP implementations. I walked the path multiple times to verify that because I could not believe it at first. This is not to say that _outside_ of Fabric this never happens, but, given the CA is using an old version of this with RSA support, this change will not impact that code.

2021-06-04 12:38 UTC, sykesm commented
> So, in Fabric, we never get a pkcs11 key because of the MSP implementations. I walked the path multiple times to verify that because I could not believe it at first. This is not to say that _outside_ of Fabric this never happens, but, given the CA is using an old version of this with RSA support, this change will not impact that code.

I'll actually go one step further. If we ever did use PKCS#11 for verification and we had any hiccup at all with a CloudHSM provider, we would have all sorts of issues in validation. That's how I started walking down the thread in the first place.

2021-06-07 16:02 UTC, denyeart commented
@mastersingh24 Based on Matt's assessment, this was a change he suggested so that the implicit assumptions in the code would become explicit, reducing any confusion in this space. As such, are you ok dismissing your comment?

2021-06-23 09:19 UTC, mastersingh24 approved these changes

2021-06-23 09:19 UTC, mastersingh24 commented
LGTM based on the comments.  @sykesm ?

2021-06-23 14:04 UTC, merged