Limit TestBlockPullerBadBlocks pullblock time
hyperledger/fabric pull request #2975
Opened 2021-10-07 12:45 UTC by Param-S

#### Type of change
- Test update

#### Description
Testcase times out after 20 minutes as the client is not able
to connect to the server.  The rootcause for the server connection
failure is not known yet.  

BlockPuller provides an option to limit the retries to get the blocks
This will help here when the client failed to connect & fail the testcase
fast. This PR set the retries to 5 times. 

#### Related issues
#2835 

Signed-off-by: Parameswaran Selvam <parselva@in.ibm.com>

2021-10-07 13:20 UTC, yacovm requested changes
Why not simply have the block puller pull the blocks asynchronously and have a select with a timeout statement that waits for either it to finish or for a timeout to expire? 

Also the title is not suitable to the content. "Orderer unittest flake in deliver_test" - you are not fixing here a flake.  Maybe say instead that you are bounding the maximum execution time of the test?

2021-10-07 19:47 UTC, yacovm commented on orderer/common/cluster/deliver_test.go
> -					closeOnce.Do(func() { close(detectedBadBlockDone) })
I don't understand why you moved this out of the logger detection closure. 
The code detects a failure and closes the channel. 

Now in the new version, you close it yourself, so you make the test artificially succeed :(

2021-10-08 06:18 UTC, Param-S commented on orderer/common/cluster/deliver_test.go
> -					closeOnce.Do(func() { close(detectedBadBlockDone) })
As per my understanding, `bp.PullBlock(10)` completes only when successful execution of this block of code`bp.Logger.WithOptions(zap.Hooks(func(entry zapcore.Entry) error`. Hence, I considered that as implicit successful bad block detection and moved down `close(detectedBadBlockDone)` after PullBlock.

2021-10-08 08:21 UTC, yacovm commented on orderer/common/cluster/deliver_test.go
> -					closeOnce.Do(func() { close(detectedBadBlockDone) })
But what if there is a bug, and it completes without having that callback be executed? We can't know for sure that a piece of code will end its execution.

2021-10-08 14:22 UTC, Param-S commented on orderer/common/cluster/deliver_test.go
> -					closeOnce.Do(func() { close(detectedBadBlockDone) })
Agree, now I moved down the pullBlock into go routine.

2021-10-08 15:06 UTC, yacovm commented on orderer/common/cluster/deliver_test.go
> -			bp.PullBlock(10)
I think we need to synchronize memory coherency otherwise we'll have a data race. 

So let's put the asynchronous block pulling in a goroutine that ends with a waitgroup waiting and then wait for that waitgroup to end, so that we have a happens-before relation.

2021-10-09 15:10 UTC, Param-S commented on orderer/common/cluster/deliver_test.go
> -			bp.PullBlock(10)
Yes, Updated the PR.

2021-10-09 16:23 UTC, yacovm commented on orderer/common/cluster/deliver_test.go
> +			var pullOnce sync.Once
Why do you need sync.Once? You close the edPullBlock channel only once anyway, there is no way it can be closed twice.

2021-10-09 16:24 UTC, yacovm commented on orderer/common/cluster/deliver_test.go
> +					close(bp.StopChannel)
Why do you need to close the StopChannel if you already have the bp.Close down below in line 1109?

2021-10-09 16:28 UTC, yacovm commented on orderer/common/cluster/deliver_test.go
> +				select {
I don't think we need a select inside a select, it's too complex. 

All we need is to synchronize the memory. Notice that when the select finishes in line 1096 we can then do another select. An alternative for memory synchronization can also be a lock. You don't have to use a channel.

2021-10-11 06:57 UTC, Param-S commented on orderer/common/cluster/deliver_test.go
> +					close(bp.StopChannel)
when times out, following statement `t.Fatalf("PullBlock did not complete within time")` terminates the current go routine, hence, it does not reach to line `bp.Close()`

2021-10-11 06:58 UTC, Param-S commented on orderer/common/cluster/deliver_test.go
> +			var pullOnce sync.Once
Since, the code block is within an testcase loop, i enclosed it within sync.Once.  I removed it now.

2021-10-11 09:32 UTC, yacovm commented on orderer/common/cluster/deliver_test.go
> +					close(bp.StopChannel)
So what? the test terminates doesn't it? Why do we care about other goroutines that are not the main goroutine if the test fails?

2021-10-11 09:44 UTC, Param-S commented on orderer/common/cluster/deliver_test.go
> +					close(bp.StopChannel)
Sorry, If i have not explained it clearly here.  When the PullBlock is not completed within the time, we want to mark that particular test(subtest) as failed.  Hence, in the select case, signaled the blocking PullBlock & then Fail the testcase by calling `t.Fatalf`

We see the following output when the PullBlock failed to return/blocked:

```
--- FAIL: TestBlockPullerBadBlocks (60.02s)
    --- FAIL: TestBlockPullerBadBlocks/nil_header (10.00s)
        deliver_test.go:1106: PullBlock did not complete within time
    --- FAIL: TestBlockPullerBadBlocks/nil_data (10.00s)
        deliver_test.go:1106: PullBlock did not complete within time
```

2021-10-11 12:46 UTC, yacovm approved these changes

2021-10-11 12:46 UTC, yacovm commented on orderer/common/cluster/deliver_test.go
> +					close(bp.StopChannel)
I'm not sure I understand, but we need to make progress

2021-10-11 12:46 UTC, merged