FAB-16120 Adding IT for MSP inconsistence
hyperledger/fabric pull request #305
Opened 2019-11-22 19:28 UTC by DereckLuo

Signed-off-by: Chongxin Luo <Chongxin.Luo@ibm.com>

- Adding integration test to replace behave test in **fabric-test**. 
- Testing correct endorsement behavior when a peer with _member_ identity trying to endorse a chaincode with _OR (Org1.peer, Org2.peer)_ endorsement policy.
- Minor typo change in integration test.

#### Type of change

- Test update

#### Description

#### Additional details

#### Related issues

2019-11-23 12:17 UTC, mastersingh24 submitted a review, later dismissed

2019-11-23 12:17 UTC, mastersingh24 commented on integration/msp/msp_test.go
> +		By("disabling NodeOY for org2, and setting all peers in org2 with member identity")
```suggestion
By("disabling NodeOU for org2, and setting all peers in org2 with member identity")
```

2019-12-02 18:32 UTC, jyellick reviewed
As best as I can tell, this test is verifying that if you set an endorsement policy to require a peer role, for an org which does not have node OUs enabled, that that org won't be able to validly endorse.  But it's not at all clear from the description of the test that this is the scenario being tested.

It actually seems like it's testing two scenarios, one, where the policy is not satisfied because the peer's signer cert does not have the peer node OU, and one where the policy is not satisfied because the peer's MSP does not define the peer node OU.  It would be nice to explicitly call this out in the test, and to name which orgs/peers are testing which scenarios.

2019-12-02 18:32 UTC, jyellick commented on integration/msp/msp_test.go
> +		By("disabling NodeOU for org2, and setting all peers in org2 with member identity")
What does "and setting all peers in org2 with member identity" mean?

2019-12-04 17:31 UTC, jyellick requested changes
The bulk of it looks good, but a few issues with the template

2019-12-04 17:31 UTC, jyellick commented on integration/nwo/configtx_template.go
> +      Rule: OR('{{.MSPID}}.member')
I don't think we want this.  Even without node-OUs, your admins should still require the admin role.

2019-12-04 17:31 UTC, jyellick commented on integration/nwo/configtx_template.go
> +      Rule: OR('{{.MSPID}}.member')
And same here

2019-12-04 17:31 UTC, jyellick commented on integration/nwo/configtx_template.go
> +    Readers:
I'd think we'd want to remove the '.peer' role from there, and add the .orderer role to both.

2019-12-05 15:19 UTC, jyellick approved these changes

2020-01-06 16:13 UTC, jyellick approved these changes

2020-01-06 16:14 UTC, merged