FAB-16408 Deprecate the Kafka based orderer
hyperledger/fabric pull request #347
Opened 2019-12-02 19:06 UTC by jyellick

#### Type of change

- Documentation update

#### Description

This PR notes the official deprecation of Kafka and urges users to
migrate to Raft.

2019-12-02 19:15 UTC, kchristidis commented on release_notes/v2.0.0.txt
> +compatibility with existing deployments, Kafka is still supported, but my be
may

2019-12-02 19:16 UTC, kchristidis requested changes
Looks good overall, small typo.

2019-12-03 03:40 UTC, kchristidis submitted a review, later dismissed

2019-12-03 03:46 UTC, guoger commented
i wanted to try the Github feature to "edit as maintainer", however forgot to add sign-off to commit message using web UI...

@jyellick sorry but pls do a force push to overwrite my edit, thx

2019-12-03 05:29 UTC, guoger approved these changes

2019-12-03 09:13 UTC, mastersingh24 approved these changes

2019-12-03 09:13 UTC, merged