[FAB-17021] Java Contract Quick Start
hyperledger/fabric pull request #371
Opened 2019-12-05 15:14 UTC by mbwhite

Signed-off-by: Matthew B White <whitemat@uk.ibm.com>

#### Type of change

- Documentation update

#### Description

Taking a quick start tutorial originally written as a github gist for RocketChat users.
Should be pushed into the main documentation

2019-12-12 08:04 UTC, mastersingh24 reviewed
more to come after I test this

2020-01-03 16:26 UTC, pamandrejko requested changes
@mbwhite 

To get started, I addressed Gari's comments and made some edits and formatting changes to align with our other tutorials.

I'd still like to address the following items:
- [ ] Need to standardize on the use of the terms `smart contract` and `chaincode` throughout the text.
- [ ] I think we should refactor these instructions to use the new Test network instead of basic-network
- [ ] I think we need to refactor these instructions to use the new cc lifecyle.
- [ ] We need to identify the appropriate location in the toc for this content - and align with the rest of our tutorial strategy.
- [ ] Don't use the fabric tools CLI - instead use the commands as Nik does in the test network.
- [ ] Decide on an appropriate title.

I'll continue to work on these changes.

2020-01-06 16:33 UTC, mastersingh24 commented on docs/README.md
> + - [Pipenv](https://pipenv.kennethreitz.org/en/latest/#install-pipenv-today)
he's the guy who actually wrote it ... not sure why he had to move it .. maybe he stopped paying for the old domain name and wanted to advertise his own name  :-)

2020-01-06 21:27 UTC, joealewine commented on docs/source/tutorial/javacontract_quickstart.md
> +
install:

Don't need "some prerequisite..."

2020-01-06 21:27 UTC, joealewine commented on docs/source/tutorial/javacontract_quickstart.md
> +
Development of what?

2020-01-06 21:27 UTC, joealewine commented on docs/source/tutorial/javacontract_quickstart.md
> +
Fabric network, not Fabric Network

2020-01-10 11:06 UTC, mbwhite commented
Closing to await https://jira.hyperledger.org/browse/FAB-17269

2020-01-10 11:06 UTC, closed without merging