Update write_first_app.rst
hyperledger/fabric pull request #3768
Opened 2022-11-08 03:08 UTC by tekintian

should run  npm run build  to build the dist/app.js, then run npm start

Signed-off-by: Tekin Tian <tekintian@gmail.com>

missing the npm run build

2022-11-08 07:57 UTC, andrew-coleman requested changes

2022-11-08 07:57 UTC, andrew-coleman commented on docs/source/write_first_app.rst
>  ``asset-transfer-basic/application-gateway-typescript`` directory, run the following command:
```suggestion
``asset-transfer-basic/application-gateway-typescript`` directory, run the following:
```

2022-11-08 07:57 UTC, andrew-coleman commented on docs/source/write_first_app.rst
>  ``asset-transfer-basic/application-gateway-typescript`` directory, run the following command:
Looks good, thanks.  Can you just make this suggested change to the wording since it is now referring to more than one command?

2022-11-08 15:04 UTC, bestbeforetoday requested changes
If the intent is to make the tutorial flow work, this change is unnecessary. If the intent is to make it easier for people to modify and re-run the sample, the instructions should probably be updated to describe the best way to do that.

2022-11-08 15:04 UTC, bestbeforetoday commented on docs/source/write_first_app.rst
> +  npm run build
The `npm install` command in the previous step already runs the TypeScript build. There is no need to explicitly run the build again, unless you are modifying the application code, in which case you can simply re-run `npm install`

2023-01-18 14:09 UTC, denyeart commented
No response from contributor, closing.

2023-01-18 14:09 UTC, closed without merging