Support for Couchdb JWT Authentation
hyperledger/fabric pull request #3929
Opened 2023-01-16 08:03 UTC by aviralagrawalDLT

Added support for couchdb JWT Authentatication via RSA256 algorithm.

Signed-off-by: Aviral Agrawal <aviral.agrawal@dltlabs.io>

#### Type of change

- New feature

#### Description

Added support for token based JWT authentication supported in Couchdb by generating JWT token using RSA256 algorithm.

#### Related issues

https://github.com/hyperledger/fabric/issues/3317

2023-01-30 14:41 UTC, ale-linux commented
Thanks @aviralagrawalDLT . This isn't a minor change and so I was wondering whether there was any kind of design document I could read first to get familiar with the objectives, the threat model etc. Also, curious about what you mean by `RSA256` - 256 is an unusual bitlength for RSA?

2023-01-31 11:08 UTC, aviralagrawalDLT commented
Hello @ale-linux 

`RSA256 `seems to be a typo from my end(Updated the same in description). It is `RS256`, which is RSA signature algorithm using SHA-256 hashing algorithm.([Reference](https://www.rfc-editor.org/rfc/rfc7518#section-3.1)). As per couchdb, they support `RS256`, `RS384 `and `RS512`([Reference ](https://github.com/apache/couchdb/blob/main/src/jwtf/README.md)). `RS256` was chosen since it is the most commonly used and while development and testing, we consumed the same. There is no major security concern apart from the fact that longer hashing algorithms are generally more secure and `RS512` token generation is faster on 64bit machine while `RS256` token generation is faster on 32bit machine but not considerably([Reference](https://crypto.stackexchange.com/a/53840)). Any suggestions otherwise on what to use would be helpful and appreciated. 

I do not have any design document handy with me right now. Give me some time to whip something up on why this change0 is being suggested.

2023-02-02 10:01 UTC, ale-linux commented
> I do not have any design document handy with me right now. Give me some time to whip something up on why this change0 is being suggested.

Thanks!

2023-05-03 07:45 UTC, cendhu requested changes
Please add unit-tests to ensure that the added feature works.

2025-04-06 21:54 UTC, denyeart commented
No activity for over a year, I'll go ahead and close for now. Please re-open if you intend to continue working on this PR.

2025-04-06 21:54 UTC, closed without merging