[FAB-17238] Refactor couchdb test in ./core/ledger/
hyperledger/fabric pull request #415
Opened 2019-12-13 12:34 UTC by DereckLuo

Signed-off-by: Chongxin Luo <Chongxin.Luo@ibm.com>

#### Type of change

- Improvement (improvement to code, performance, etc)

#### Description

- Refactor couchdb tests in ./core/ledger/... Only starting couchDB container
ones for all couchdb unit tests.
- Fix couchdb containers not being cleaned up after tests complete.

#### Additional details

#### Related issues

https://jira.hyperledger.org/browse/FAB-17238

2019-12-16 09:59 UTC, mastersingh24 requested changes

2019-12-16 09:59 UTC, mastersingh24 commented on core/ledger/util/couchdbtest/couchdbTest.go
> +/*
we don't really use camelCase for filenames.  I'd justname the file `couchdb.go`

2019-12-16 09:59 UTC, mastersingh24 commented on core/ledger/util/couchdbtest/couchdbTest.go
> +	return couchDB.Address(), func() { couchDB.Stop() }
```suggestion
return couchDB.Address(), func() {
     couchDB.Stop()
     os.Unsetenv("COUCHDB_ADDR")
}

2019-12-16 09:59 UTC, mastersingh24 commented on core/ledger/util/couchdbtest/couchdbTest.go
> +// CouchDBCleanup cleans up external couchDB resource
I'd remove ... see suggestion above

2019-12-16 10:00 UTC, mastersingh24 reviewed
Looks good overall ... just a couple of suggestions

2019-12-17 12:14 UTC, DereckLuo commented
thanks for the review, changes has been applied. it is much cleaner than original solution.

2019-12-17 12:25 UTC, mastersingh24 approved these changes

2019-12-18 11:53 UTC, mastersingh24 commented
I'm overriding this ... another gossip flake ... not going to waste another CI cycle

2019-12-18 11:53 UTC, merged