CouchDB index support for implicit collections
hyperledger/fabric pull request #4794
Opened 2024-04-04 08:10 UTC by bkiran6398

Allow CouchDB index creation on implicit collection of organisations.

Indexes can be created for specific organisation's implicit collections at:
`META-INF/statedb/couchdb/collections/_implicit_org_<MSP_ID>` directory of the chaincode package.

Common indexes for all the organisations' implicit collection can be created at:
`META-INF/statedb/couchdb/collections/_implicit_org_*` directory of the chaincode package.
( `*` acts as wildcard for all organisation MSP ids. )

#### Type of change

- New feature

#### Description
Updated chaincode deployment handler to check if the indexes are for implicit collection if given collection directory name not explicitly defined in collection config. If the implicit collection indexes belong this handling peer's organisation or passed as global implicit collection indexes (using `*` notation), then indexes are created on corresponding implicit collection.

#### Additional details
- Please review the way of fetching `localMspId` directly using `viper` at `NewDB` constructor function.
- Added few more tar file entries to represent implicit collection indexes in unit tests. (However UT `TestHandleChainCodeDeployOnCouchDB` was already failing due to some other error)

#### Related issues
- #4780

2024-04-19 12:21 UTC, denyeart requested changes
Sorry for the delay but I wanted to actually test it myself since there was no integration test here. This is an overall good approach, thank you for filling this gap!

In my test I found that the implicit collection wildcard approach causes an error at deploy time:

`Error: error getting chaincode bytes: walk failed: metadata file path or name is not supported: META-INF/statedb/couchdb/collections/_implicit_org_*/indexes/`

This is because of this validation that doesn't allow asterisk:

https://github.com/hyperledger/fabric/blob/main/internal/ccmetadata/validators.go#L31

2024-04-19 12:21 UTC, denyeart commented on core/ledger/kvledger/txmgmt/privacyenabledstate/db.go
> +	return &DB{vdb, metadataHint, viper.GetString("peer.localMspId")}, nil
Getting the config from within the implementation is considered a bad practice. We use the dependency injection pattern to pass down dependencies including peer configuration.
In this case, in kv_ledger_provider.go when calling privacyenabledstate.NewDBProvider() you can pass the existing 
 `p.initializer.MembershipInfoProvider.MyImplicitCollectionName()`.

2024-04-19 12:35 UTC, denyeart commented
We'll want an integration test for both the single org use case and all org use case.
It should be feasible to extend the existing CouchDB index integration test here:
https://github.com/hyperledger/fabric/blob/main/integration/ledger/couchdb_indexes_test.go

2024-04-19 12:57 UTC, denyeart commented
Not many people use Windows for Fabric, but still, asterisk is now allowed in Windows directory names. Maybe use `_implicit_all_orgs`?

2025-04-23 19:35 UTC, C0rWin commented
Not active for more than one year, closing it for the meantime.

2025-04-23 19:35 UTC, closed without merging