chore: fix some typos in comments
hyperledger/fabric pull request #4808
Opened 2024-04-10 07:01 UTC by goodfirm

#### Type of change

- Bug fix
- New feature
- Improvement (improvement to code, performance, etc)
- Test update
- Documentation update

#### Description

fix some typos in comments

#### Additional details

#### Related issues

2024-04-10 07:37 UTC, ale-linux approved these changes, later dismissed

2024-04-10 08:34 UTC, satota2 requested changes
@goodfirm I have found some minor corrections. Please check it.

2024-04-10 08:34 UTC, satota2 commented on core/ledger/kvledger/state_listener_test.go
> +	// Simulate tx3 - this nighter conflicts with tx1 nor with tx2
@goodfirm It seems like 'neither' is the correct word, not 'nighter'.
```suggestion
	// Simulate tx3 - this neither conflicts with tx1 nor with tx2
```

2024-04-11 02:17 UTC, goodfirm commented on core/ledger/kvledger/state_listener_test.go
> +	// Simulate tx3 - this nighter conflicts with tx1 nor with tx2
Thanks! Modified

Please review again

2024-04-12 01:24 UTC, satota2 commented
@goodfirm Thank you for the update. It seems there is still a typo in the revised version: "neighter" should be corrected to "neither." Could I kindly ask you to make this correction once more?

2024-04-14 12:44 UTC, goodfirm commented
> @goodfirm Thank you for the update. It seems there is still a typo in the revised version: "neighter" should be corrected to "neither." Could I kindly ask you to make this correction once more?

Of course, thank you for your comment.

Modified

2024-04-15 03:00 UTC, satota2 approved these changes
@goodfirm  Thank you for your updates. LGTM!

2024-04-15 03:34 UTC, merged