Fix struct names
hyperledger/fabric pull request #4819
Opened 2024-04-16 03:09 UTC by coderwander

#### Type of change

- Documentation update

#### Description

Fix struct names 

#### Additional details

#### Related issues

2024-04-16 09:48 UTC, satota2 requested changes
@coderwander 
I have commented on the minor modifications. Please confirm it.

2024-04-16 09:48 UTC, satota2 commented on core/scc/inprocstream.go
> +// InProcStream interface for stream between Peer and chaincode instance.
```suggestion
// inProcStream interface for stream between Peer and chaincode instance.
```
For name consistency, it should start with a lowercase letter.

2024-04-16 10:41 UTC, coderwander commented on core/scc/inprocstream.go
> +// InProcStream interface for stream between Peer and chaincode instance.
Thanks. Modified

2024-04-16 20:57 UTC, C0rWin approved these changes

2024-04-17 00:59 UTC, satota2 approved these changes
@coderwander Thank you for your updates.

2024-04-17 00:59 UTC, merged