add unit test against a real grpc server for common/deliverclient/blo…
hyperledger/fabric pull request #4826
Opened 2024-04-24 19:55 UTC by solo-daemon

* Test update

### Description
fix https://github.com/hyperledger/fabric/issues/4567

Added unit test for deliveryRequester.

2024-05-07 07:38 UTC, tock-ibm requested changes

2024-05-07 07:38 UTC, tock-ibm commented on common/deliverclient/blocksprovider/delivery_requester_test.go
> +		ds.t.Fatalf("timed out waiting for seek assertions to receive a value\n")
This can be t.Fatal() rather than t.Fatalf()

2024-05-07 07:38 UTC, tock-ibm commented on common/deliverclient/blocksprovider/delivery_requester_test.go
Thanks for your contribution!
This PR is incomplete. Please move it to draft until you finish or tag it as WIP.
- Please don't remove the tests that use mocks, just add tests that communicate with a real grpc server
- Send a seek info message and check it is received
- Respond with a block and check it is received
- Check connecting with TLS and connection errors

2024-05-11 16:06 UTC, Williams23678 commented
Hello how to access free bitcoin

2024-05-11 16:06 UTC, Williams23678 commented
Is it possible to access bitcoin?

2024-05-11 16:10 UTC, Williams23678 commented on common/deliverclient/blocksprovider/delivery_requester_test.go
> +	"crypto/x509"
5 BTC

2025-04-08 12:04 UTC, C0rWin commented
@solo-daemon I'm following up on this pull request for adding unit tests against a real gRPC server for the delivery client.

This PR has been open since April 2024 with no activity since May 2024. There has been no response to @tock-ibm's comments or any updates to address the concerns raised.

Given the lack of recent activity and unaddressed feedback, we're considering closing this PR. If you're still interested in contributing these tests, please let us know and address the outstanding comments.

If we don't hear back soon, we'll close this PR. You're welcome to reopen it or create a new PR when you have time to continue work on this improvement.

2025-04-27 18:55 UTC, tock-ibm commented
Since there is no activity, we're closing this PR.
You're welcome to reopen it or create a new PR when you have time to continue work on this improvement.

2025-04-27 18:55 UTC, closed without merging