[FAB-17517] Only Initialize specified provider
hyperledger/fabric pull request #769
Opened 2020-02-28 21:06 UTC by ahmedsajid

#### Type of change

- Bug fix

#### Description

Code currently tries to initialize multiple providers based on
provided config Opts being nil or not.

This update ensures that only specified provider is initialized
based on ProviderName.

This fixes "Failed initializing PKCS11.BCCSP %!s(<nil>)" error
when the code complied with PKCS11 or PLUGINS enabled expect
configuration to not be nil even when Provider is set to SW.

Signed-off-by: Ahmed Sajid <ahmed.sajid@securekey.com>

#### Additional details

If this looks good I can do PR for release-2.0 and master.

#### Related issues

https://jira.hyperledger.org/browse/FAB-17517

2020-02-29 02:33 UTC, denyeart commented
The unit test failure is due to a gossip test flake, which is common in release-1.4.
Regardless, please add your own unit test to verify the fix and then we try to get all the unit tests to pass.

2020-03-02 22:05 UTC, ahmedsajid commented
@denyeart I have added unit tests.
Let me know anything else that needs fixing.

2020-03-03 14:54 UTC, ahmedsajid commented
/ci-run

2020-03-03 15:52 UTC, gbolo commented
Good job @ahmedsajid

2020-03-08 15:10 UTC, fqutishat approved these changes

2020-03-10 02:47 UTC, btl5037 commented
The change looks good. But in general we open changes against the master branch and cherry pick them into earlier releases.

2020-03-10 02:50 UTC, ahmedsajid commented
@btl5037
The initial testing was done on v1.4.5.
Shall I open PR for Master and release-2.0?

2020-03-11 12:30 UTC, mastersingh24 approved these changes

2020-03-11 12:30 UTC, merged

2020-03-11 12:32 UTC, sykesm requested changes
Comments are too late, I guess.

2020-03-11 12:32 UTC, sykesm commented on bccsp/factory/nopkcs11.go
> +		return errors.Errorf("%s\nCould not find default `%s` BCCSP", factoriesInitError, config.ProviderName)
Looks like you've simply copied a bad practice that exists in the code: errors are not messages and do not contain new lines.

2020-03-11 12:32 UTC, sykesm commented on bccsp/factory/pkcs11_test.go
> +	assert.NotContains(t, err.Error(), "Failed initializing PLUGIN.BCCSP")
When we know the error, we use EqualError. That means we should have a single assertion here instead of 3.

2020-03-11 12:32 UTC, sykesm commented on bccsp/factory/nopkcs11_test.go
> +	factoriesInitError = nil
You're calling the unexported method - why is this required?

2020-03-11 12:32 UTC, sykesm commented on bccsp/factory/nopkcs11_test.go
> +	factoriesInitError = nil
Same thing here. Not sure why we need to reset the error when we're calling the unexported function directly.

2020-03-11 12:32 UTC, sykesm commented on bccsp/factory/nopkcs11.go
> +			return errors.Wrapf(err, "Failed initializing PLUGIN.BCCSP %s", factoriesInitError)
`factoriesInitError` should not be used here. It has not ben set yet.

2020-03-11 12:32 UTC, sykesm commented on bccsp/factory/nopkcs11.go
> +		return errors.Errorf("%s\nCould not find default `%s` BCCSP", factoriesInitError, config.ProviderName)
`factoriesInitError` should not be used here. It has not been set yet. (It's set by the caller `Once`.)

2020-03-11 12:32 UTC, sykesm commented on bccsp/factory/nopkcs11_test.go
> +Copyright IBM Corp. 2016 All Rights Reserved.
It's no longer 2016.

2020-03-11 12:32 UTC, sykesm commented on bccsp/factory/pkcs11.go
> +	if config.ProviderName == "PKCS11" && config.Pkcs11Opts != nil {
The pkcs11 side should be made consistent with the nopkcs11 side. The `factoriesInitError` package state is not handled the same in the two methods. This is confusing and is causing odd constructs in the tests.

`factoriesInitError` should be set as a result of the once and not here.