don't wait to expire dead endpoints if exiting
hyperledger/fabric pull request #964
Opened 2020-03-31 19:42 UTC by MHBauer

#### Type of change

- Bug fix

#### Description

deadEndpoints channel gets filled up. Exit occurs, and deadEndpoints is not drained. We can avoid putting more into the channel and creating hanging goroutines (many many many of them, this fills up my memory). There are still messages that get dropped on the floor sometimes that will cause a different hang.

#### Additional details

#### Related issues

FAB-17451 I reported this from https://github.com/hyperledger/fabric/pull/954#issuecomment-606809081

2020-03-31 19:44 UTC, MHBauer commented
@denyeart maybe #3 from your bug. The build log had expired.

2020-03-31 21:01 UTC, yacovm commented on gossip/comm/comm_impl.go
> +	case <-c.exitChan:
maybe return here?

2020-03-31 22:33 UTC, MHBauer commented on gossip/comm/comm_impl.go
> +	case <-c.exitChan:
sure.

2020-04-01 04:46 UTC, MHBauer commented
That would be the other flake I mean.

/ci-run

2020-04-01 05:20 UTC, MHBauer commented
flake is https://jira.hyperledger.org/browse/FAB-16233

/ci-run

2020-04-01 10:15 UTC, yacovm requested changes
Please keep this pull request focused and not have in it commits that are unrelated

2020-04-03 01:44 UTC, MHBauer commented
moved to separate PR #983. I would suggest merging that one first if this keeps flakin.

2020-04-03 15:19 UTC, yacovm approved these changes

2020-04-03 15:19 UTC, merged