Update tutorials overview for test network
hyperledger/fabric pull request #972
Opened 2020-04-01 18:39 UTC by nikhil550

Signed-off-by: NIKHIL E GUPTA <negupta@us.ibm.com>

#### Type of change

- Documentation update

#### Description

Update tutorial page overview to reflect new tutorials and deprecation of BYFN

2020-04-01 19:16 UTC, pamandrejko requested changes

2020-04-01 19:16 UTC, pamandrejko commented on docs/source/tutorials.rst
> +Fabric in production, see the guide for :doc:`deployment_guide_overview`.
Hyperledger

2020-04-01 21:37 UTC, nikhil550 commented on docs/source/tutorials.rst
> +Fabric in production, see the guide for :doc:`deployment_guide_overview`.
done.

2020-04-03 16:11 UTC, nikhil550 commented
Responding to comments that the test net doc should be in the tutorials as well, to make things a bit easier to find

2020-04-08 12:04 UTC, pamandrejko approved these changes
Good to see this in the Tutorial toc now

2020-04-08 12:05 UTC, merged

2020-04-08 12:05 UTC, pamandrejko commented
@Mergifyio backport release-2.0

2020-04-08 12:13 UTC, nikhil550 commented
@Mergifyio backport release-2.1